config/routes.rb
Rails.application.routes.draw do

  resources :lists

  root 'pages#home'

  get 'pages/about'

  get 'pages/contact'

  get 'categories/:id' => 'categories#show',as: :category

  get 'categories/:category_id/subcategories/:id' => 'subcategories#show', as: :category_subcategory

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :lists
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :category
  belongs_to :subcategory
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category,only: [:show]
  def show
  	@lists=List.where(category_id:params[:id])
  end
private
	def set_category
		@category= Category.find(params[:id])
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
    @category_options = Category.all.map {|c| [c.nombre.capitalize,c.id]}
    # select categorias y subcategorias separados
    #@subcategory_options=[]
    #@category_options.each do |cat|
    #@subcategory_options<<Subcategory.where(category_id:cat[1]).map{|c| [c.nombre,c.id]}
    # end
    # select group categorias/subcategorias
    @subcategory_options={}
    @category_options.each do |v,c|
      @subcategory_options.store(v, Subcategory.where(category_id:c).map{|sub|[sub.nombre,sub.id]})   
    end
    
  end

  # GET /lists/1/edit
  def edit
    @category_options = Category.all.map {|c| [c.nombre.capitalize,c.id]}
    @subcategory_options={}
    @category_options.each do |v,c|
      @subcategory_options.store(v, Subcategory.where(category_id:c).map{|sub|[sub.nombre,sub.id]})   
    end

  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.category_id = @list.subcategory.category_id

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:titulo, :descripcion, :category_id, :subcategory_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@category= Category.all
  end

  def about
  end

  def contact
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: [:show]
  def show
  	@category= Category.find(@subcategory.category_id)
  	@category_name=@category.nombre
  	@lists= List.where(subcategory_id: params[:id])
  end

  private
  def set_subcategory
  	@subcategory= Subcategory.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/categories/show.html.erb
<h1><%= @category.nombre.upcase %></h1>
<ul>
	<% Subcategory.where(category_id:@category.id).each do |sc| %>
	<li><%= link_to sc.nombre,category_subcategory_path(@category,sc) %></li>
	<% end %>
</ul>
<%= render '/lists/index' %>
<br>
<%= link_to 'Regresar', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Img</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
	<ul>
		<li><%= link_to 'Categorias', root_path %> </li>
		<li><%= link_to 'Clasificados', lists_path %></li>		
		<li><%= link_to 'Nuevo clasificado', new_list_path %></li>
		<li><%= link_to 'About', pages_about_path %> </li>
		<li><%= link_to 'Contac',pages_contact_path %> </li>
	</ul>

</nav>
<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <!-- select group catagoria/subcategoria -->
  <div class="field">
    <%= f.label 'Categoría' %><br>
    <%= f.select :subcategory_id, grouped_options_for_select(@subcategory_options,@list.subcategory_id),{prompt: 'Escoja opción'}, {required: true} %> <!-- include_blank: true -->
  </div>
<!-- Select separados categoriaysubcategoría
   <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select :category_id,@category_options %>
  </div>
  
  <div class="field">
  <%= f.label :subcategory_id %><br>  
    <% @subcategory_options.each do |cat| %>      
      <%= f.select :subcategory_id, cat,{},{class: :aaa}%>  
    <% end %>
  </div> -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista clasificados</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descripcion</th>
      <th>Category</th>
      <th>Subcategory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.titulo %></td>
        <td><%= list.descripcion %></td>
        <td><%= list.category.nombre %></td>
        <td><%= list.subcategory.nombre %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<%= render 'index' %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @list.titulo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @list.descripcion %>
</p>

<p>
  <strong>Category:</strong>
  <%= @list.category.nombre %>
</p>

<p>
  <strong>Subcategory:</strong>
  <%= @list.subcategory.nombre %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/pages/contact.html.erb
<h1>Contact Page</h1>

app/views/pages/home.html.erb
<h1>Craig list clone</h1>
<p>ROR Development</p>

<% @category.each do |c|%>
	<%= link_to c.nombre.upcase, c %> ||>>
	<% Subcategory.where(category_id:c.id).each do |sc| %>
	<%= link_to sc.nombre,category_subcategory_path(c,sc) %>
	<% end %>
	<br>
<% end %>

app/views/subcategories/show.html.erb
<h1><%= @category_name.upcase%></h1>
<p>Subcategoria: <%= @subcategory.nombre.capitalize %></p>
<%= render '/lists/index' %>
<br>
<%= link_to 'Regresar',@category%>